/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WrongAnswersRouteImport } from './routes/wrong-answers'
import { Route as StudyRouteImport } from './routes/study'
import { Route as ResultRouteImport } from './routes/result'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RandomExamRouteImport } from './routes/random-exam'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LiveRouteImport } from './routes/live'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BookmarksRouteImport } from './routes/bookmarks'
import { Route as AiTeacherRouteImport } from './routes/ai-teacher'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as ApiAiTeacherChatRouteImport } from './routes/api/ai-teacher-chat'
import { Route as SubjectsSubjectIndexRouteImport } from './routes/subjects.$subject.index'
import { Route as ExamSubjectChapterRouteImport } from './routes/exam.$subject.$chapter'

const WrongAnswersRoute = WrongAnswersRouteImport.update({
  id: '/wrong-answers',
  path: '/wrong-answers',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomExamRoute = RandomExamRouteImport.update({
  id: '/random-exam',
  path: '/random-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksRoute = BookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const AiTeacherRoute = AiTeacherRouteImport.update({
  id: '/ai-teacher',
  path: '/ai-teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTeacherChatRoute = ApiAiTeacherChatRouteImport.update({
  id: '/api/ai-teacher-chat',
  path: '/api/ai-teacher-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIndexRoute = SubjectsSubjectIndexRouteImport.update({
  id: '/subjects/$subject/',
  path: '/subjects/$subject/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamSubjectChapterRoute = ExamSubjectChapterRouteImport.update({
  id: '/exam/$subject/$chapter',
  path: '/exam/$subject/$chapter',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-teacher': typeof AiTeacherRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/random-exam': typeof RandomExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/study': typeof StudyRoute
  '/wrong-answers': typeof WrongAnswersRoute
  '/api/ai-teacher-chat': typeof ApiAiTeacherChatRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/exam/$subject/$chapter': typeof ExamSubjectChapterRoute
  '/subjects/$subject/': typeof SubjectsSubjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-teacher': typeof AiTeacherRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/random-exam': typeof RandomExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/study': typeof StudyRoute
  '/wrong-answers': typeof WrongAnswersRoute
  '/api/ai-teacher-chat': typeof ApiAiTeacherChatRoute
  '/subjects': typeof SubjectsIndexRoute
  '/exam/$subject/$chapter': typeof ExamSubjectChapterRoute
  '/subjects/$subject': typeof SubjectsSubjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-teacher': typeof AiTeacherRoute
  '/bookmarks': typeof BookmarksRoute
  '/dashboard': typeof DashboardRoute
  '/leaderboard': typeof LeaderboardRoute
  '/live': typeof LiveRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/random-exam': typeof RandomExamRoute
  '/register': typeof RegisterRoute
  '/result': typeof ResultRoute
  '/study': typeof StudyRoute
  '/wrong-answers': typeof WrongAnswersRoute
  '/api/ai-teacher-chat': typeof ApiAiTeacherChatRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/exam/$subject/$chapter': typeof ExamSubjectChapterRoute
  '/subjects/$subject/': typeof SubjectsSubjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-teacher'
    | '/bookmarks'
    | '/dashboard'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/profile'
    | '/random-exam'
    | '/register'
    | '/result'
    | '/study'
    | '/wrong-answers'
    | '/api/ai-teacher-chat'
    | '/subjects/'
    | '/exam/$subject/$chapter'
    | '/subjects/$subject/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-teacher'
    | '/bookmarks'
    | '/dashboard'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/profile'
    | '/random-exam'
    | '/register'
    | '/result'
    | '/study'
    | '/wrong-answers'
    | '/api/ai-teacher-chat'
    | '/subjects'
    | '/exam/$subject/$chapter'
    | '/subjects/$subject'
  id:
    | '__root__'
    | '/'
    | '/ai-teacher'
    | '/bookmarks'
    | '/dashboard'
    | '/leaderboard'
    | '/live'
    | '/login'
    | '/profile'
    | '/random-exam'
    | '/register'
    | '/result'
    | '/study'
    | '/wrong-answers'
    | '/api/ai-teacher-chat'
    | '/subjects/'
    | '/exam/$subject/$chapter'
    | '/subjects/$subject/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiTeacherRoute: typeof AiTeacherRoute
  BookmarksRoute: typeof BookmarksRoute
  DashboardRoute: typeof DashboardRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LiveRoute: typeof LiveRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RandomExamRoute: typeof RandomExamRoute
  RegisterRoute: typeof RegisterRoute
  ResultRoute: typeof ResultRoute
  StudyRoute: typeof StudyRoute
  WrongAnswersRoute: typeof WrongAnswersRoute
  ApiAiTeacherChatRoute: typeof ApiAiTeacherChatRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
  ExamSubjectChapterRoute: typeof ExamSubjectChapterRoute
  SubjectsSubjectIndexRoute: typeof SubjectsSubjectIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wrong-answers': {
      id: '/wrong-answers'
      path: '/wrong-answers'
      fullPath: '/wrong-answers'
      preLoaderRoute: typeof WrongAnswersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random-exam': {
      id: '/random-exam'
      path: '/random-exam'
      fullPath: '/random-exam'
      preLoaderRoute: typeof RandomExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks': {
      id: '/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof BookmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-teacher': {
      id: '/ai-teacher'
      path: '/ai-teacher'
      fullPath: '/ai-teacher'
      preLoaderRoute: typeof AiTeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/subjects'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-teacher-chat': {
      id: '/api/ai-teacher-chat'
      path: '/api/ai-teacher-chat'
      fullPath: '/api/ai-teacher-chat'
      preLoaderRoute: typeof ApiAiTeacherChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subject/': {
      id: '/subjects/$subject/'
      path: '/subjects/$subject'
      fullPath: '/subjects/$subject/'
      preLoaderRoute: typeof SubjectsSubjectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exam/$subject/$chapter': {
      id: '/exam/$subject/$chapter'
      path: '/exam/$subject/$chapter'
      fullPath: '/exam/$subject/$chapter'
      preLoaderRoute: typeof ExamSubjectChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiTeacherRoute: AiTeacherRoute,
  BookmarksRoute: BookmarksRoute,
  DashboardRoute: DashboardRoute,
  LeaderboardRoute: LeaderboardRoute,
  LiveRoute: LiveRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RandomExamRoute: RandomExamRoute,
  RegisterRoute: RegisterRoute,
  ResultRoute: ResultRoute,
  StudyRoute: StudyRoute,
  WrongAnswersRoute: WrongAnswersRoute,
  ApiAiTeacherChatRoute: ApiAiTeacherChatRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
  ExamSubjectChapterRoute: ExamSubjectChapterRoute,
  SubjectsSubjectIndexRoute: SubjectsSubjectIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
